services:
  app:
    build: .
    container_name: fcs-frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - proxy

networks:
  proxy:
    external: true
